import type { NextPage } from 'next';
import { Typography } from '@mui/material';

export const metadata = {
	title: 'Devxian : skill',
	description: 'Generated by create next app',
};

const Skill: NextPage = () => {
	return <Typography>skill</Typography>;
};

export default Skill;
