'use client';

import type { NextPage, Metadata } from 'next';
import { Text } from '@/components/atoms';

export const metadata: Metadata = {
    title: 'Devxian',
    description: 'Generated by create next app',
};

const Index: NextPage = () => {
    return <Text>hi</Text>;
};

export default Index;
