import type { NextPage, Metadata } from 'next';
import { Home } from '@/components/templates';

export const metadata: Metadata = {
    title: 'Devxian',
    description: 'Generated by create next app',
};

const Index: NextPage = () => {
    return <Home />;
};

export default Index;
