import type { NextPage, Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Devxian',
    description: 'Generated by create next app',
};

const Index: NextPage = () => {
    return <div>hi</div>;
};

export default Index;
